import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../../components/Sidebar";
import Login from "../../components/Login";
import { getServerSession } from 'next-auth';
import { SessionProvider } from '../../components/SessionProvider'; // Updated import
import { authOptions } from "../../pages/api/auth/[...nextauth]";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions); // Ensure getServerSession is used synchronously
  console.log('session', session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              {/* Sidebar */}
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <Sidebar />
              </div>
              
              {/* Client Provider - Notification */}
              <div className="bg-[#343541] flex-1">
                {children}
              </div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
